In [347]:
import investpy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import requests

from pprint import PrettyPrinter
from pprint import PrettyPrinter

In [348]:
# Read the CSV file into a DataFrame
df = pd.read_csv('XAUUSD.csv')
df['date'] = pd.to_datetime(df['date'])
df['time'] = df['date'].dt.time
df['date'] = df['date'].dt.date
df.set_index('time', inplace=True)
df

FileNotFoundError: [Errno 2] No such file or directory: 'XAUUSD.csv'

In [ ]:
# df.head(10)
df = df.dropna()

In [ ]:
df.info()
# print(df.columns)

<class 'pandas.core.frame.DataFrame'>
Index: 276 entries, 00:00:00 to 23:45:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    276 non-null    object 
 1   open    276 non-null    float64
 2   high    276 non-null    float64
 3   low     276 non-null    float64
 4   close   276 non-null    float64
dtypes: float64(4), object(1)
memory usage: 12.9+ KB


In [ ]:
# Data Preprocessing
# TODO: Add dataengineering to the model





# df['date'] = pd.to_datetime(df['date'])
# df.set_index('date', inplace=True)
# df

In [ ]:
# Splitting the Data
X = df[['open', 'high', 'low', 'close']]
y = df[['open', 'high', 'low', 'close']]
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)


print(f"X_train shape: {X_train.shape} \nX_test shape: {X_test.shape} \ny_train shape: {y_train.shape} \ny_test shape: {y_test.shape}")

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (220, 4) 
X_test shape: (56, 4) 
y_train shape: (220, 4) 
y_test shape: (56, 4)
X_train shape: (220, 4)
X_test shape: (56, 4)
y_train shape: (220, 4)
y_test shape: (56, 4)


In [ ]:
# Model Selection and Training
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
# Model Evaluation
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")
print(y_pred)

Mean Squared Error: 2.0771834578619557e-26
[[1975.01502 1976.56006 1974.88501 1976.40991]
 [1957.29248 1957.30005 1954.30493 1956.46509]
 [1973.34497 1975.63    1972.80005 1975.63   ]
 [1959.45508 1960.01489 1958.88989 1959.94507]
 [1974.06848 1976.21509 1973.60498 1974.92505]
 [1983.10498 1984.82398 1980.5     1982.23657]
 [1958.88196 1963.11499 1958.88196 1962.90991]
 [1978.05493 1978.15991 1977.60498 1977.66504]
 [1963.13049 1963.95996 1962.81543 1963.08496]
 [1959.41553 1959.71509 1958.3335  1958.87451]
 [1972.91992 1973.04004 1971.72498 1972.16992]
 [1957.09009 1957.1499  1954.57007 1955.23999]
 [1977.47705 1978.28198 1974.67993 1975.67651]
 [1959.64502 1959.92993 1958.4425  1958.63   ]
 [1968.83008 1969.03394 1966.53247 1967.27502]
 [1961.35156 1961.69995 1957.80005 1959.41504]
 [1959.92505 1960.33008 1959.19995 1959.33496]
 [1973.40295 1974.6499  1972.276   1972.74353]
 [1971.95996 1972.26001 1971.69507 1971.96753]
 [1973.31006 1975.17993 1972.19751 1972.64002]
 [1976.90991 1977

In [ ]:
#
pp = PrettyPrinter()

In [ ]:
#  GEtting the data from the API
url = "https://marketdata.tradermade.com/api/v1/live"
currency = "XAUUSD"
date = "2023-05-22"
year = "2010,2011,2012,2013,2014,2015,2016,2017,2018,2019"

with open('api_key.txt', 'r') as file:
    api_key = file.read().strip()

data_list = []

# Iterate over each 15-minute interval
for hour in range(0, 24):
    for minute in range(0, 60, 15):
        # Construct the query parameters for the API request
        querystring = {
            "currency": currency,
            "date": date,
            "hour": hour,
            "minute": minute,
            "api_key": api_key
        }

        # Send the API request
        response = requests.get(url, params=querystring)

        # Process the response data
        response_data = response.json()
        quotes = response_data['quotes']

        # Iterate over each quote in the response
        for quote in quotes:
            date = pd.to_datetime(response_data['requested_time'])
            open_price = quote['mid']
            high = quote['mid'] + 1.0
            low = quote['mid'] - 1.0
            close = quote['mid']

            data_list.append([date, open_price, high, low, close])

# Create a DataFrame from the data list
df_real_time = pd.DataFrame(data_list, columns=['date', 'open', 'high', 'low', 'close'])

# Save the DataFrame to a CSV file
df_real_time.to_csv('XAUUSD_realtime.csv', index=False)

# Convert date and time columns to proper datetime format
df_real_time['date'] = pd.to_datetime(df_real_time['date'])
df_real_time['time'] = df_real_time['date'].dt.time
df_real_time['date'] = df_real_time['date'].dt.date

# Set the time column as the DataFrame's index
df_real_time.set_index('time', inplace=True)

# Display the DataFrame
df_real_time.head()


date       open       high        low      close
time                                                            
22:16:33  2023-05-31  1963.9775  1964.9775  1962.9775  1963.9775
22:16:34  2023-05-31  1963.9775  1964.9775  1962.9775  1963.9775
22:16:35  2023-05-31  1963.9675  1964.9675  1962.9675  1963.9675
22:16:36  2023-05-31  1963.9675  1964.9675  1962.9675  1963.9675
22:16:37  2023-05-31  1963.9400  1964.9400  1962.9400  1963.9400

In [ ]:
live_df = pd.read_csv('XAUUSD_realtime.csv')
live_df = live_df.drop(columns=['date'])
df = df.drop(columns=['date'])

KeyError: "['date'] not found in axis"

In [ ]:
df

open        high         low       close
time                                                    
00:00:00  1980.91992  1981.40991  1979.16992  1979.28491
00:15:00  1979.27490  1980.02002  1978.91003  1978.96997
00:30:00  1978.97498  1980.28491  1978.43506  1980.12500
00:45:00  1980.13000  1981.37012  1979.55493  1981.07007
01:00:00  1981.10998  1982.44507  1980.52490  1980.66992
...              ...         ...         ...         ...
22:45:00  1959.05005  1961.92993  1958.97998  1961.10498
23:00:00  1961.10010  1961.10010  1959.83008  1960.09009
23:15:00  1960.09497  1960.10498  1959.04504  1959.45996
23:30:00  1959.46997  1959.66504  1958.12500  1959.48511
23:45:00  1959.49512  1960.21509  1959.47510  1959.84009

[276 rows x 4 columns]

In [349]:
live_df

open       high        low      close
0   1963.9775  1964.9775  1962.9775  1963.9775
1   1963.9775  1964.9775  1962.9775  1963.9775
2   1963.9675  1964.9675  1962.9675  1963.9675
3   1963.9675  1964.9675  1962.9675  1963.9675
4   1963.9400  1964.9400  1962.9400  1963.9400
..        ...        ...        ...        ...
91  1963.8726  1964.8726  1962.8726  1963.8726
92  1963.8726  1964.8726  1962.8726  1963.8726
93  1963.8726  1964.8726  1962.8726  1963.8726
94  1963.8726  1964.8726  1962.8726  1963.8726
95  1963.9875  1964.9875  1962.9875  1963.9875

[96 rows x 4 columns]

In [350]:
train_df, test_df = train_test_split(df_real_time, test_size=0.2, random_state=42)
print("Training set shape:", train_df.shape)
print("Test set shape:", test_df.shape)

Training set shape: (76, 5)
Test set shape: (20, 5)


In [351]:
X_live = df[['open', 'high', 'low', 'close']]
y_live = df[['open', 'high', 'low', 'close']]
X_train_live, X_test_live, y_train_live, y_test_live = train_test_split(
X_live, y_live, test_size=0.2, random_state=42)

In [352]:
y_pred_live = model.predict(X_test_live)
mse_live = mean_squared_error(y_test_live, y_pred_live)
print(f"Mean Squared Error: {mse_live}")
print(y_pred_live)

Mean Squared Error: 2.0771834578619557e-26
[[1975.01502 1976.56006 1974.88501 1976.40991]
 [1957.29248 1957.30005 1954.30493 1956.46509]
 [1973.34497 1975.63    1972.80005 1975.63   ]
 [1959.45508 1960.01489 1958.88989 1959.94507]
 [1974.06848 1976.21509 1973.60498 1974.92505]
 [1983.10498 1984.82398 1980.5     1982.23657]
 [1958.88196 1963.11499 1958.88196 1962.90991]
 [1978.05493 1978.15991 1977.60498 1977.66504]
 [1963.13049 1963.95996 1962.81543 1963.08496]
 [1959.41553 1959.71509 1958.3335  1958.87451]
 [1972.91992 1973.04004 1971.72498 1972.16992]
 [1957.09009 1957.1499  1954.57007 1955.23999]
 [1977.47705 1978.28198 1974.67993 1975.67651]
 [1959.64502 1959.92993 1958.4425  1958.63   ]
 [1968.83008 1969.03394 1966.53247 1967.27502]
 [1961.35156 1961.69995 1957.80005 1959.41504]
 [1959.92505 1960.33008 1959.19995 1959.33496]
 [1973.40295 1974.6499  1972.276   1972.74353]
 [1971.95996 1972.26001 1971.69507 1971.96753]
 [1973.31006 1975.17993 1972.19751 1972.64002]
 [1976.90991 1977

In [353]:
# Prepare the features for prediction
X_realtime = df_real_time[['open', 'high', 'low', 'close']]
print(X_realtime)

# Check dimensions
if X_realtime.shape[0] != y_pred.shape[0]:
    print("Error: Number of rows in X_realtime and y_pred do not match.")
elif X_realtime.shape[0] != 1:
    print("Error: X_realtime should have only one row.")
else:
    # Get the single row from X_realtime
    X_row = X_realtime.iloc[0]

    # Initialize an empty list to store the comparison results
    comparison = []

    # Iterate over each row in y_pred
    for y_pred_row in y_pred:
        # Compare X_row with y_pred_row element-wise
        row_comparison = np.allclose(X_row, y_pred_row)
        comparison.append(row_comparison)

    # Create a DataFrame to display the comparison results
    comparison_df = pd.DataFrame(comparison, columns=['Comparison'])

    # Concatenate X_realtime, y_pred, and the comparison DataFrame
    df_comparison = pd.concat([pd.DataFrame(X_row).T, pd.DataFrame(y_pred, columns=X_realtime.columns), comparison_df], axis=1)

    # Output the comparison DataFrame
    print(df_comparison)


               open       high        low      close
time                                                
22:16:33  1963.9775  1964.9775  1962.9775  1963.9775
22:16:34  1963.9775  1964.9775  1962.9775  1963.9775
22:16:35  1963.9675  1964.9675  1962.9675  1963.9675
22:16:36  1963.9675  1964.9675  1962.9675  1963.9675
22:16:37  1963.9400  1964.9400  1962.9400  1963.9400
...             ...        ...        ...        ...
22:17:45  1963.8726  1964.8726  1962.8726  1963.8726
22:17:45  1963.8726  1964.8726  1962.8726  1963.8726
22:17:46  1963.8726  1964.8726  1962.8726  1963.8726
22:17:47  1963.8726  1964.8726  1962.8726  1963.8726
22:17:48  1963.9875  1964.9875  1962.9875  1963.9875

[96 rows x 4 columns]
Error: Number of rows in X_realtime and y_pred do not match.
